[package]
name    = "tar-example"
version = "0.4.3"
authors = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]

[dependencies]
nom = "^2.1.0"
afl = "^0.1.5"
afl-plugin = "^0.1.5"

[dependencies.tar-parser]
path = "../.."
