[package]
name    = "tar-example"
version = "0.3.1"
authors = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]

[dependencies]
nom = { git = "https://github.com/Keruspe/nom" }
afl = "^0.1.3"
afl-plugin = "^0.1.3"

[dependencies.tar-parser]
path = "../.."
