[package]
name    = "tar-example"
version = "0.3.1"
authors = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]

[dependencies]
nom = { git = "https://github.com/Keruspe/nom" }

[dependencies.tar-parser]
path = "../.."
